### ISSUE TITLE
No able to use on Pandas.Series data with native index

### ISSUE THREAD

**Issue by arul67800** [LawrentChen/pandas_upsert_to_mysql#1]
File "<ipython-input-34-3a0f080aab53>", line 4, in <module>
    if_row_exists='update')

  File "C:\Users\Dell\anaconda3\lib\site-packages\pangres\core.py", line 187, in upsert
    dtype=dtype)

  File "C:\Users\Dell\anaconda3\lib\site-packages\pangres\helpers.py", line 125, in __init__
    fields = list(df.index.names) + df.columns.tolist()

  File "C:\Users\Dell\anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'columns'

**Comment by LawrentChen** [comment]
Hi, arul67800. Sorry for this late reply, which is pretty late I guess... Since I went back to school, I haven't been maintaining this repo actively and didn't notice this...

As for your issue, indeed pandas_upsert_to_mysql does not support using a Series object. If you want to do so, maybe you should transform the Series into a DataFrame first.

```python
df = pd.DataFrame(your_series)
```

And I still highly recommend [pangres](https://github.com/ThibTrip/pangres) instead of my solution, suggest you take a loook for it.

Let me know if you need any further information, or I can close this issue. Cheers~
